### ISSUE TITLE
small layout issue, text overlapping in protocol description

### ISSUE THREAD

**Issue by willcanine** [OpenTrons/opentrons-app#41]
![screenshot 2016-11-08 17 26 05](https://cloud.githubusercontent.com/assets/1382562/20119931/9125d18e-a5d8-11e6-94ae-2360d06a4d67.png)

**Comment by Kadee80** [comment]
since the protocols dont have the ability to store dates etc yet, can we just remove the date created until   we have the ability to store data created?

**Comment by levthedev** [comment]
no, this issue is still a problem - we now display the last modified date for protocols, which is not hard coded but derived from the OS. so this text clipping issue is still present.

**Comment by Kadee80** [comment]
got it, css fix pending
