### ISSUE TITLE
need some indication of which pipette is on 'left' and 'center'

### ISSUE THREAD

**Issue by willcanine** [OpenTrons/opentrons-app#42]
![screenshot 2016-11-08 17 27 30](https://cloud.githubusercontent.com/assets/1382562/20119954/adec01e4-a5d8-11e6-8077-d4db1a51e9f8.png)

**Comment by levthedev** [comment]
Agreed. Do we want to use left and center or a and b here? I use a and b for the notification when you save ("successfully saved p200 on the a axis", or something like that) but that can be changed. We should be consistent though.

**Comment by Kadee80** [comment]
Pantea had suggested calling it left and right. Its more clear and there is
no 3rd pipette. I'm fine with whatever. Simple conditional
