### ISSUE TITLE
uneven spacing error between 'top' and 'bottom'

### ISSUE THREAD

**Issue by willcanine** [OpenTrons/opentrons-app#43]
![screenshot 2016-11-08 17 31 58](https://cloud.githubusercontent.com/assets/1382562/20120097/4a1323a4-a5d9-11e6-864a-7f15ba576d50.png)

**Comment by levthedev** [comment]
I think this might've been on purpose from Katie? I can check with her and if not we can fix it.

**Comment by Kadee80** [comment]
Yes on purpose.
Top is physically much higher than the other 3 more clustered positions.
Added the spacing for clarity.
Based on a discussion tomorrow I can amend images and spacing accordingly.

**Comment by levthedev** [comment]
Closing this unless there are any objections.
