### ISSUE TITLE
I dont think it should prevent me from clicking while it moves

### ISSUE THREAD

**Issue by willcanine** [OpenTrons/opentrons-app#44]
it is nice to be able to push the jog button multiple times in a row and have the robot be very responsive, like in current app. otherwise it is frustrating, like 'why is the robot stopping me!'

**Comment by levthedev** [comment]
We had issues with robot movements during protocol upload breaking the app and rapid jogging messing things up, so we just disabled everything until it finishes moving. I have some ideas about how to circumvent this issue that I'll look into tomorrow.
