### ISSUE TITLE
robot should home when done with run

### ISSUE THREAD

**Issue by willcanine** [OpenTrons/opentrons-app#45]

**Comment by levthedev** [comment]
It homes before a run, do you want it to do both?

**Comment by andySigler** [comment]
This would be for feature parity with 1.2, however it's not required for accuracy like the one before running. Seems to me it's similar to homing automatically on connect, and if we are saying we shouldn't assume everyone wants to home on connect, then we should also not assume everyone wants to home after protocol runs.

**Comment by levthedev** [comment]
Yeah, I agree with @andySigler. I think homing before a run is necessary so that it doesn't crash, but homing on connect or after a run seem superfluous and unexpected.
